### ISSUE TITLE
how to get the NNUE file ?

### ISSUE THREAD

**Issue by tissatussa** [cosmobobak/viridithas#141]
while compiling i have an error at the end : it can't find the NNUE file .. i looked for it, but the (v12.0.0) asset ZIP doesn't contain it .. so i tried to `git clone` the newest source (PR 140), even with the `--recursive` option, but the NNUE file isn't downloaded that way .. 

then i re-found (my) #83 and this gave the perfect answer : how to download the (newest) NNUE file and also how to compile (on Linux), not using the `makefile` .. your #83 info also works with the newest Viridithas, so i managed to compile : a valid binary v13.0.0-dev is created, with filesize 23.9 Mb .. this is a lot bigger than previous versions !?

can you elaborate on this ?
you could mention this in the README, i think most people will use the `makefile` ..

[ i'm on Xubuntu 22.04 ]

**Comment by cosmobobak** [comment]
Yes, the new NNUE is significantly larger than previous, because it has nine king buckets and therefore significantly more parameters than before, and I'm also yet to apply some of the compression techniques that can be used (LEB encoding, king feature-plane merging). I'll add a section to the README on compilation soon.

**Comment by cosmobobak** [comment]
Build instructions added to the README in https://github.com/cosmobobak/viridithas/commit/eefa0c8f079cbfcc5e8d11228d373922c66b9468, I hope future compiles are easier!
